apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "token-vesting-claim-site.fullname" . }}
  labels:
    {{- include "token-vesting-claim-site.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "token-vesting-claim-site.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "token-vesting-claim-site.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.tokenVestingClaimSite.image.repository }}:{{ .Values.tokenVestingClaimSite.image.version }}"
          imagePullPolicy: {{ .Values.tokenVestingClaimSite.image.pullPolicy }}
          env:
            - name: NEXT_PUBLIC_RPC_URL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.nextPublicRpcUrl }}
                  key: nextPublicRpcUrl
            - name: NEXT_PUBLIC_VESTING_CONTRACT_ADDRESS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.nextPublicVestingContractAddress }}
                  key: nextPublicVestingContractAddress
            - name: NEXT_PUBLIC_APP_TITLE
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.nextPublicAppTitle }}
                  key: nextPublicAppTitle
            - name: NEXT_PUBLIC_APP_DESCRIPTION
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.nextPublicAppDescription }}
                  key: nextPublicAppDescription
            - name: NEXT_PUBLIC_TOKEN_SYMBOL
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.nextPublicTokenSymbol }}
                  key: nextPublicTokenSymbol
            - name: NEXT_PUBLIC_TOKEN_DECIMALS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.secret.nextPublicTokenDecimals }}
                  key: nextPublicTokenDecimals
            - name: NODE_ENV
              value: "{{ .Values.env }}"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      restartPolicy: Always
