replicaCount: 1
env: production
nameOverride: ""
fullnameOverride: ""
cron:
  schedule: 0 * * * *
  endpoint: /api/fractalstats
secret:
  nextPublicRpcUrl: https://orchard.rpc.quai.network
  nextPublicVestingContractAddress: 0x0056e37Cf10e1183540E86027D7821A8AE3a7b93
  nextPublicAppTitle: Quai Token Vesting Claims
  nextPublicAppDescription: Check and claimd your vested QUAI tokens
  nextPublicTokenSymbol: QUAI
  nextPublicTokenDecimals: 18
tokenVestingClaimSite:
  image:
    repository: quainetwork/token-vesting-claims-site
    version: v0.1.0-pre
    pullPolicy: IfNotPresent
