replicaCount: 1
env: production
nameOverride: ""
fullnameOverride: ""
cron:
  schedule: 0 * * * *
  endpoint: /api/fractalstats
secret:
  nextPublicRpcUrl: token-vesting-claim-site
  nextPublicVestingContractAddress: token-vesting-claim-site
  nextPublicAppTitle: token-vesting-claim-site
  nextPublicAppDescription: token-vesting-claim-site
  nextPublicTokenSymbol: token-vesting-claim-site
  nextPublicTokenDecimals: token-vesting-claim-site
tokenVestingClaimSite:
  image:
    repository: quainetwork/token-vesting-claim-site
    version: v0.2.0-pre
    pullPolicy: IfNotPresent
