name: Auto Dev Workflow
on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-dev-common.yml@main
    with:
      needs_build: true
      needs_export: false
      needs_docker: false
      install_command: "npm ci"
      cloud_deploy: false
      skip_deploy: true
      update_version: false
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      BUILD_ARGS: 'NEXT_PUBLIC_RPC_URL=https://orchard.rpc.quai.network,NEXT_PUBLIC_VESTING_CONTRACT_ADDRESS=0x0056e37Cf10e1183540E86027D7821A8AE3a7b93,NEXT_PUBLIC_APP_TITLE="Quai Token Vesting Claims",NEXT_PUBLIC_APP_DESCRIPTION="Check and claim your vested Quai tokens",NEXT_PUBLIC_TOKEN_SYMBOL=QUAI,ID_ADMIN=1235140843766288455,NEXT_PUBLIC_TOKEN_DECIMALS=18'
      DOCKER_BUILD_ARGS: 'NEXT_PUBLIC_RPC_URL=https://orchard.rpc.quai.network,NEXT_PUBLIC_VESTING_CONTRACT_ADDRESS=0x0056e37Cf10e1183540E86027D7821A8AE3a7b93,NEXT_PUBLIC_APP_TITLE="Quai Token Vesting Claims",NEXT_PUBLIC_APP_DESCRIPTION="Check and claim your vested Quai tokens",NEXT_PUBLIC_TOKEN_SYMBOL=QUAI,ID_ADMIN=1235140843766288455,NEXT_PUBLIC_TOKEN_DECIMALS=18'
