name: Auto Dev Workflow
on:
  pull_request:
    types: [closed]
    branches: [ "main" ]
jobs:
  call-common-workflow:
    uses: dominant-strategies/quai-cicd/.github/workflows/deploy-dev-common.yml@main
    with:
      needs_build: true
      needs_export: false
      needs_docker: false
      install_command: "npm ci"
      cloud_deploy: false
      skip_deploy: true
      update_version: false
    secrets:
      GH_PAT: ${{ secrets.GH_PAT }}
      BUILD_ARGS: 'NEXT_PUBLIC_INTERCOM_APP_ID=crmoyy2i,NEXT_PUBLIC_ADDRESS=https://claims.dev.qu.ai,NEXT_PUBLIC_PROJECT_ID=169d0b6c2496e7b36b210a91a7215a09,NEXT_PUBLIC_KYC_PAYMENT_ADDRESS=0x72bB98f9de3FA19614375D860bD3973e44dAB3B8,NEXT_PUBLIC_ENABLE_TESTNETS=false,ID_ADMIN=1235140843766288455,,1252955036820963331,,474440190480613397,IP_ADMIN=46.229.60.129,,46.39.148.182,,72.182.96.176'
      DOCKER_BUILD_ARGS: 'NEXT_PUBLIC_INTERCOM_APP_ID=crmoyy2i,NEXT_PUBLIC_ADDRESS=https://claims.dev.qu.ai,NEXT_PUBLIC_PROJECT_ID=169d0b6c2496e7b36b210a91a7215a09,NEXT_PUBLIC_KYC_PAYMENT_ADDRESS=0x72bB98f9de3FA19614375D860bD3973e44dAB3B8,NEXT_PUBLIC_ENABLE_TESTNETS=false,ID_ADMIN=1235140843766288455,,1252955036820963331,,474440190480613397,IP_ADMIN=46.229.60.129,,46.39.148.182,,72.182.96.176'
